
trigger:
- main
- feature/*

pool: Dev-Agent-pool

jobs:
- job: install_init_plan
  displayName: init_plan
  pool: Dev-Agent-pool
  steps:
  - task: TerraformInstaller@1
    displayName: terraform install
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    displayName: init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'identity-federation-spn'
      backendAzureRmResourceGroupName: 'Backend-rg'
      backendAzureRmStorageAccountName: 'rkbkdstg'
      backendAzureRmContainerName: 'rk-container'
      backendAzureRmKey: 'tatefile.tf'
  - task: TerraformTask@5
    displayName: plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'identity-federation-spn'
- job: apply
  displayName: apply
  pool: Dev-Agent-pool
  steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-- auto-approve'
      environmentServiceNameAzureRM: 'identity-federation-spn'
  