
trigger:
- main
- feature/*

pool: Dev-Agent-pool

jobs:
- job: install_init_plan             #job1
  displayName: init_plan
  # pool: Dev-Agent-pool
  steps:
  - task: TerraformInstaller@1
    displayName: terraform install
    inputs:
      terraformVersion: 'latest'

  # - task: TerraformTask@5
  #   displayName: init
  #   inputs:
  #     provider: 'azurerm'
  #     command: 'init'
  #     backendServiceArm: 'identity-federation-spn'
  #     backendAzureRmResourceGroupName: 'Backend-rg'
  #     backendAzureRmStorageAccountName: 'rkbkdstg'
  #     backendAzureRmContainerName: 'rk-container'
  #     backendAzureRmKey: 'tatefile.tf'
  - task: TerraformTask@5
    displayName: init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'identity-federation-spn'
      backendAzureRmResourceGroupName: 'backend-rg'
      backendAzureRmStorageAccountName: 'stgstate'
      backendAzureRmContainerName: 'terraformstate'
      backendAzureRmKey: 'state.tf'
  - task: TerraformTask@5
    displayName: plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'identity-federation-spn'
  #     commandOptions: '-out=rkplan'

  # - publish: rkplan
  #   artifact: job1plan
- job: Manual_validation            #Job2
  displayName: manual_validation
  dependsOn: install_init_plan
  pool: server
  steps:
  - task: ManualValidation@1
    inputs:
      notifyUsers: '2ranjeetkr@gmail.com'
      approvers: '2ranjeetkr@gmail.com'
      instructions: 'please check plane and approve.'


- job: apply                        #Job3 
  displayName: apply
  # pool: Dev-Agent-pool
  dependsOn: Manual_validation
  steps:
  
  - task: TerraformTask@5           #we need to run init again in job2 beform apply
    displayName: init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'identity-federation-spn'
      backendAzureRmResourceGroupName: 'Backend-rg'
      backendAzureRmStorageAccountName: 'rkbkdstg'
      backendAzureRmContainerName: 'rk-container'
      backendAzureRmKey: 'tatefile.tf'

  # - download: current     #pipeline id, current means artifect will download from current pipeline
  #   artifact:  job1plan
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'identity-federation-spn'
  