trigger:
- main

pool: rk-agent-pool
stages:
- stage: Scann_validate
  displayName: Scann_validate
  
  jobs:
  - job: Scann_validate
    displayName: Terraform Validate

    steps:
    - checkout: self
    - task: tfsec@1
      displayName: tfsec
      inputs:
        version: 'v1.26.0'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          cd $(Build.SourcesDirectory)
          tflint
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Manual_Sc_with_App_register'
        backendAzureRmResourceGroupName: 'pintra01'
        backendAzureRmStorageAccountName: 'pintrastore01'
        backendAzureRmContainerName: 'pintracontainer'
        backendAzureRmKey: 'state.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

  - job: Plan
    displayName: Terraform Plan
    dependsOn: Scann_validate
    condition: succeeded()

    steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Manual_Sc_with_App_register'
        backendAzureRmResourceGroupName: 'pintra01'
        backendAzureRmStorageAccountName: 'pintrastore01'
        backendAzureRmContainerName: 'pintracontainer'
        backendAzureRmKey: 'state.tfstate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'Manual_Sc_with_App_register'

  - job: Manual_Validation
    displayName: Manual validation
    dependsOn: Plan
    condition: succeeded()
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: '2ranjeetkr@gmail.com'
        instructions: 'pls approve'

  - job: Apply
    dependsOn: Manual_Validation
    condition: succeeded()
    displayName: Apply
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Manual_Sc_with_App_register'
        backendAzureRmResourceGroupName: 'pintra01'
        backendAzureRmStorageAccountName: 'pintrastore01'
        backendAzureRmContainerName: 'pintracontainer'
        backendAzureRmKey: 'state.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'Manual_Sc_with_App_register'


